/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation
 The sidebars can be generated from the filesystem, or explicitly defined here.
 Create as many sidebars as you want.
 */
// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  DocSidebar: [{type: 'autogenerated', dirName: '.'}],
  Skill: [

    {
      label: 'Docusaurus',
      type: 'category',
      link: {
        type: 'doc',
        id: 'skill/docusaurus/docusaurus-guides',
      },
      items: [
        'skill/docusaurus/docusaurus-translate',
        'skill/docusaurus/docusaurus-component',
        'skill/docusaurus/docusaurus-comment',
        'skill/docusaurus/docusaurus-deploy',
      ],
    },
  ],
  Note: [
    'skill/skill',

    {

      label: '学习笔记',
      type: 'category',
      link: {
        type: 'doc',
        id: 'skill/skill-Academy',
      },
      items: [
        'note/SSL/1',
        'note/SSL/ssl',
      ],
    },
    {
      label: '技术笔记',
      type: 'category',
      link: {
        type: 'doc',
        id: 'note/intro',
      },
      items: [
        'skill/CS-miss-Lesson',
        {
          label: 'Git',
          type: 'category',
          link: { type: 'generated-index' },
          items: [
            {
              type: 'autogenerated',
              dirName: 'skill/Git',
            },
          ],
        },
        {
          label: 'Docusaurus',
          type: 'category',
          link: { type: 'generated-index' },
          items: [
            {
              type: 'autogenerated',
              dirName: 'skill/docusaurus',
            },
          ],
        },

      ],
    },
    {
      label: '编程语言',
      type: 'category',
      link: { type: 'generated-index' },
      items: [
        {
          label: 'Java',
          type: 'category',
          link: { type: 'generated-index' },
          items: [
            {
              type: 'autogenerated',
              dirName: 'skill/programming-languages/java',
            },
          ],
        },
        {
          label: 'Python',
          type: 'category',
          link: { type: 'generated-index' },
          items: [
            {
              type: 'autogenerated',
              dirName: 'skill/programming-languages/python',
            },
          ],
        },
        {
          label: 'C++',
          type: 'category',
          link: { type: 'generated-index' },
          items: [
            {
              type: 'autogenerated',
              dirName: 'skill/programming-languages/C++',
            },
          ],
        },
      ],
    },
  ],
};

export default sidebars;
