/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation
 The sidebars can be generated from the filesystem, or explicitly defined here.
 Create as many sidebars as you want.
 */
// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  DocSidebar: [{type: 'autogenerated', dirName: '.'}],
  Skill: [
    'skill/test',
    {
      label: 'Docusaurus',
      type: 'category',
      link: {
        type: 'doc',
        id: 'skill/docusaurus/docusaurus-guides',
      },
      items: [
        'skill/docusaurus/docusaurus-translate',
        'skill/docusaurus/docusaurus-component',
        'skill/docusaurus/docusaurus-comment',
        'skill/docusaurus/docusaurus-deploy',
      ],
    },
  ],
  Note: [
    'note/introduction',
    'note/CS-miss-Lesson',
    'note/Git/git',
    'note/Git/git+'
  ],
};

export default sidebars;
